# This is a basic workflow to help you get started with Actions

name: Deploy Node app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /root/repos/skeleton-node-ms
            git pull origin main
            docker-compose restart
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Github Actions Bot
          DISCORD_EMBEDS: |
            [{
              "title": "${{ github.repository }}",
              "url": "https://github.com/${{ github.repository }}",
              "description": ":white_check_mark: [prod - ${{ github.event_name }}]. App se desplegó exitosamente por [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{github.sha}})."
            }]




     