# This is a basic workflow to help you get started with Actions

name: Deploy Node app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd /root/repos/skeleton-node-ms
            git pull origin main
            docker-compose restart
            echo "ok"
            whoami




     
